# -*- coding: utf-8 -*-
"""z1_zmienne_operatory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qRKqYbV3ZlpeXGZAB-WJUzF9l9_-NNSi

# Zmienne


- Zmienna - **nazwane** miejsce w pamięci, pozwala na zapisywanie i odczytywanie danych
- Nazwy zmiennych mogą zawierać litery, cyfry i \_, muszą zaczynać się literą lub \_
- Python rozróżnia wielkość liter
"""

# TODO: zadeklarować kilka zmiennych: int, float, str, bool, pokazać NameError

a = 3
print(a)

b = 3.4
print(b)

napis = "aaa"
print(napis)

napis

A

"""### Print
funkcja print() drukuje
"""

# TODO: wydruk

print('Wartość zmiennej a: ', a)

"""### Przypisanie
znak = oznacza przypisanie, czyli podstawienie prawej strony do lewej
"""

# TODO: przypisanie, inkrementacja

c = a + b
print(c)

x = 1
print(x)

x = x + 1
print(x)

"""### Typy

- int (integer) liczby całkowite
- float liczby zmiennoprzecinkowe
- str (string) napisy
- bool logiczny (0 lub 1, prawda lub fałsz)
"""

# TODO: type

type(x)

type(b)

type(napis)

# True, False z dużej
logiczna = False
print(logiczna)

"""Działanie operatora/funkcji może zależeć od typu zmiennych wejściowych"""

a + b

napis + a

"""### Konwersje typów"""

# TODO: int/str, ValueError

napis + ' ' + str(a)

a='bbb'

a

type(a)

a = 5
type(a)

"""### Operatory
- dodawanie +
- odejmowanie -
- mnożenie \*
- dzielenie /
- dzielenie // bez reszty
- modulo (reszta z dzielnia) %
- potęgowanie \**
"""

2/3

2//3

8 % 5

2 ** 4

"""### Kolejność działań
- nawiasy ()
- potęgowanie
- mnożenie i dzielenie
- dodawanie i odejmowanie
- od lewej do prawej

### Zadanie 1
- Przypisać wartości 2 i 3 do zmiennych a i b
- podstawić do zmiennej c wynik $\frac{b}{2a} + \frac{5}{a + b}(4a - b)^3$
- wydrukować c
"""

# TODO: szkielet zadania + wzór do wypełnienia

a = 2
b = 3
c = b / (2 * a) + 5 / (a + b) * (4 * a - b) ** 3
print(c)

b / (2 * a)

"""### Biblioteki"""

import math
math.sqrt(4)
# instalacja dodatkowych pip install biblioteka

math.pi

"""### Zadanie 2
Policzyć i wydrukować objętość i pole powierzchni stożka ściętego - na podstawie przypisanyhc wartości R, r i h.
$$V=\frac{1}{3} πh(R^2+Rr+r^2)$$
$$l=\sqrt{h^2 + (R-r)^2}$$
$$P_b=πl(R+r)$$

"""

import math

r = 3
R = 4.5
h = 5
V = 1/3 * math.pi * h * (R ** 2 + R * r + r ** 2)
l = math.sqrt(h ** 2 + (R - r) ** 2)
Pb = math.pi * l * (R + r)
print('objetość: ', V)
print('Pole powierzchni bocznej: ', Pb)

V

type(V)

